version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: rails s -p 80 -b '0.0.0.0'
    volumes:
      - vendor_bundle:/vendor/bundle
      - ../metamask-login-rails-vue:/app:cached
    ports:
      - "3000:80"
    tty: true
    stdin_open: true
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres:10.1
    environment:
      - POSTGRES_USER=manager
      - POSTGRES_PASSWORD=password
    ports:
      - "15432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
volumes:
  vendor_bundle: {}
  postgres:
    driver: local
