version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: rails s -p 80 -b '0.0.0.0'
    volumes:
      - ../metamask-login-rails-vue:/app:cached
    ports:
      - "3000:80"
    tty: true
    stdin_open: true
